### ISSUE TITLE
Expose heroku_addon config_vars values

### ISSUE THREAD

**Issue by clementmangin** [heroku/terraform-provider-heroku#140]
I need to extract the value of a configuration variable that a `heroku_addon` adds to my `heroku_app`. This is to configure an AWS lambda function that needs to connect to this addon.

However, the `config_vars` attribute on `heroku_addon` does not export a map of configuration variables and their values, but only a list of the variables' names.

Here's what a typical config may look like:

```
resource "heroku_app" "worker" {
  app  = "worker"
}

resource "heroku_addon" "cloudamqp" {
  app  = "${heroku_app.worker.name}"
  plan = "cloudamqp:lemur"
}

output "cloudamqp_config_vars" {
  value = "${heroku_addon.cloudamqp.config_vars}"
}
```

And the output it gives.

```
cloudamqp_config_vars = [
    CLOUDAMQP_APIKEY,
    CLOUDAMQP_URL
]
```

Would it be possible to get a map instead, so I could extract the value I need?

**Comment by clementmangin** [comment]
Thank you @davidji99 for your thorough answer, this is very helpful!

For now I've resorted to:

1. adding the config vars I need for my Lambda function as input variables,
2. using placeholder values for the first `terraform apply`,
3. getting the actual values using `heroku config:get`,
3. running `terraform apply` again with the actual values.

I've subscribed to the PR you indicated in case there are any news on this front.

**Comment by talbright** [comment]
FWIW there's also https://devcenter.heroku.com/articles/app-webhooks which could allow you to do things in an event driven fashion. I'm not sure if this is more or less viable for you situation, but something to keep in mind.

**Comment by crisp2u** [comment]
Hi guys, I hit the same issue while trying to provision the cloudamqp addon. I noticed that the Platform API supports this `https://api.heroku.com/addons/cloudamqp/config` which give the name/value list for the add on config. this means that we can at least have a `heroku_addon_config` data source or populate the values in the existing `heroku_addon` datasource. Any plans to implement this ? Also in the meantime, any idea how I can achieve the same thing ?

**Comment by davidji99** [comment]
Hi @crisp2u,

Execute a `GET` on that endpoint could work; however if I recall correctly, addon providers set their config vars asynchronously so we might need to poll for the addon configs. BUT, if the provider exposes the configs as part of the existing addon data source, I don't foresee any issues. I could be wrong here. I can take a look at exposing this attribute after a few other of my PRs are done.
