### ISSUE TITLE
Variables in Source URL of `heroku_build` not interpolated

### ISSUE THREAD

**Issue by TimSpence** [heroku/terraform-provider-heroku#222]
### Terraform Version
```
$ terraform --version
Terraform v0.12.4
+ provider.heroku v2.0.1
```

### Heroku Provider Version
```
$ terraform --version
Terraform v0.12.4
+ provider.heroku v2.0.1
```

### Affected Resource(s)
Please list the resources as a list, for example:
- heroku_build

### Terraform Configuration Files

*main.tf:*
```hcl
resource "heroku_app" "integration_beta" {
  name = "reflektive-secret-app"
  region = "us"
  stack = "${var.heroku_stack}"

  organization {
    name = "reflektive-secret-org"
  }
}

resource "heroku_build" "integration_beta" {
  app = "${heroku_app.integration_beta.id}"
  buildpacks = [
    "https://github.com/heroku/heroku-buildpack-ruby.git",
    "https://github.com/gunpowderlabs/buildpack-ruby-rake-deploy-tasks"
  ]

  source = {
    url = "https://${var.token}@github.com/PulseSoftwareInc/private-repo/archive/${var.release_version}.tar.gz"
    version = "${var.release_version}"
  }
}

```
*variables.tf:*
```
variable "release_version" {
  description = "The release tag that goes with the private repo URL"
}

variable "token" {
  description = "Your personal token for accessing the private Github repo"
}
```

*terraform.tfvars:*
```
token = "TRUST-ME-A-VALID-GITHUB-PERSONAL-TOKEN"
release_version = "v1.0.0"
```

### Debug Output
https://gist.github.com/TimSpence/0864948644df3b0220024100d042f124

### Panic Output
N/A

### Expected Behavior
Terraform should interpolate `token` and `release_version`, producing a valid URL for the release archive.

### Actual Behavior
The variables are not interpolated, so `terraform validate` and `terraform plan` fail because the URL does not match the expression `/^https://`.

If I replace the `token` variable reference with the actual Github Personal Token, the command works as expected.  However I do not want to commit an OAuth token to a repository, even though it is private.

### Steps to Reproduce
1. `terraform init`
2. `terraform validate`

### References
According to [this Terraform issue](https://github.com/hashicorp/terraform/issues/18929), `Terraform 0.12` changed behavior to parse and interpolate variables when the configuration is loaded.

**Comment by davidji99** [comment]
Hi @TimSpence,

Quick question...I'm guessing you already rotated this token?  https://gist.github.com/TimSpence/0864948644df3b0220024100d042f124#file-gistfile1-txt-L67 your

**Comment by TimSpence** [comment]
Hi @davidji99 ,

Thank you for pointing out the token in the gist.  I replaced the UUID in the debug output with a generated one *before* creating the gist.

I think the actual behavior is odd as well for that same reason.  Hopefully I have some time this weekend to dive into the code and resolve this.

**Comment by mars** [comment]
Hi @TimSpence ,

Like David, I do not understand how `heroku_build.source.url` is not returning the interpolated string. That is a fundamental Terraform/HCL feature, not something unique to the Heroku provider.

Either there's a mistake being made pasting the evidence in this issue, or something must be confused in your setup.

Please let us know if you have any updates about this! 🙇‍♂️

**Comment by Jac2NL** [comment]
I get the interpolated strings with:
 
```
Terraform v0.12.26
+ provider.heroku v2.4.1
```
Of course the reason for doing all this is that you want to build from a private repository. Even if interpolation works, the problem remains that the user's personal access token is stored in the Terraform state. And Heroku does not appear to support deploy keys. So you cannot access the private repo through SSH instead of HTTPS.

**Comment by mars** [comment]
> Variables in Source URL of heroku_build not interpolated

This issue was fixed by using a new Terraform version, over a year ago.
