### ISSUE TITLE
Support the SNI endpoint for Heroku SSL

### ISSUE THREAD

**Issue by michaelherold** [heroku/terraform-provider-heroku#250]
## Terraform Version

v0.12.21

### Heroku Provider Version

v2.2.2

### Affected Resource(s)

- `heroku_cert`, although this is probably a new resource

### Terraform Configuration Files

```hcl
resource "heroku_cert" "ssl_certificate" {
	app = heroku_app.development.name
	certificate_chain = file("${var.cert_chain_file}")
	private_key = file("${var.cert_key}")
}
```

### Debug Output

Not applicable.

### Panic Output

Not applicable.

### Expected Behavior

Heroku SSL should be used instead of SSL:Endpoint whenever possible. This uses SNI certificates instead of single certificates and is the preferred way of handling SSL on Heroku now.

### Actual Behavior

The Terraform provider requires the SSL:Endpoint add-on to handle certificates.

### Steps to Reproduce

Following the [documentation in the provider guide](https://www.terraform.io/docs/providers/heroku/r/cert.html).

### Important Factoids

Heroku released their Heroku SSL offering for SSL management in lieu of the SSL:Endpoint add-on [in September 2016](https://blog.heroku.com/ssl-is-now-included-on-all-paid-dynos). Since then, this has been the preferred way of handling SSL management.

It would be great if Terraform could use this system instead of the older SSL:Endpoint add-on. Looking at the CLI code, which I have linked below, it seems like this should be a pretty easy task because they are API-compatible.

I would be happy to implement this -- or have one of my colleagues do so -- if I can get some guidance on how you would like this to be implemented. It _feels_ like it should be a separate resource from `heroku_cert` - perhaps `heroku_ssl_cert` because this is for Heroku SSL?

### References

*Code References*

- [Path lookup in Heroku's CLI](https://github.com/heroku/cli/blob/v7.39.0/packages/certs-v5/commands/certs/add.js#L29-L55)
- [Path lookup in Heroku's CLI, part 2](https://github.com/heroku/cli/blob/v7.39.0/packages/certs-v5/lib/endpoints.js#L26-L41)
- [HTTP request in Heroku's CLI](https://github.com/heroku/cli/blob/v7.39.0/packages/certs-v5/commands/certs/add.js#L239-L244)

*Heroku Documentation References*

- [SSL page](https://devcenter.heroku.com/articles/ssl)

**Comment by bernerdschaefer** [comment]
This is actually interesting and a bit tricky.

While the SSL endpoint _addon_ is indeed no longer the preferred choice, the SSL Endpoint API resources (without the addon) are still used to manage certificates for apps in Private Spaces. The CLI figures out which endpoints to use.

Most of the provider's current users are either using [Automated Certificate Management](https://devcenter.heroku.com/articles/automated-certificate-management) (`acm = true` on `heroku_app` resource) or are using `heroku_cert` for apps in Private Spaces, so this isn't something that's come up.

We should definitely support SNI certs, though! My first thought would be to add an optional `type` field to the `heroku_cert` resource which defaults to `endpoint` (so current uses continue to work) but which can be set to `sni` to use the alternate endpoint.

**Comment by davidji99** [comment]
Looks like the Platform APIs have the SNI endpoints listed here https://devcenter.heroku.com/articles/platform-api-reference#sni-endpoint so this modification/addition should be doable.

Looking for differences between the SNI-Endpoint API and the SSL-Endpoint, there are minor differences namely:
- `GET` returns app information for SSL-Endpoint.
- `PATCH` has an additional argument in its request body: `preprocess`. However, `heroku_cert` always defaults this value to `true`.

Since both are separate endpoints for the platform API, having separate resources for SSL & SNI `heroku_sni_cert` would keep the code a bit cleaner and not force us to litter `if/else` in the code. Plus if one wished to modify `heroku_cert` to support SNI, additional testing would be needed to ensure existing TF configurations by users will be `noop`.

**Comment by adielcristo** [comment]
I'd like to add an use case to the discussion:

I tried to add a pair of [Cloudflare Origin CA certificates](https://support.cloudflare.com/hc/en-us/articles/115000479507-Managing-Cloudflare-Origin-CA-certificates) using the instructions in the [provider docs](https://registry.terraform.io/providers/heroku/heroku/latest/docs/resources/cert).

The certificates were added to the application and the setup was validated following the instructions in the [Heroku DevCenter](https://devcenter.heroku.com/articles/ssl#verify-ssl-is-setup-correctly).

Even so, the certificates were not listed in the Heroku dashboard and the Cloudflare setup resulted in an `Error 525: SSL handshake failed`. When I added the same certificates manually using the Heroku dashboard (using the SNI endpoint) the setup worked without problems.

I believe this is a use case for supporting the SNI endpoint.

**Comment by AndriusJonaitis** [comment]
I have the same issue as @adielcristo, cannot import Cloudflare Origin CA certificate using Terraform and currently I have to import it manually as shown in the [Heroku Dev Center](https://devcenter.heroku.com/articles/ssl#manually-uploading-certificates-and-intermediaries).

Because of this I am not able to fully control infrastructure with Terraform.

Are there any news or workarounds solving this problem?

**Comment by davidji99** [comment]
Hi @AndriusJonaitis,

You could use a `local-exec` combined with the heroku CLI to get you closer to managing your infrastructure completely with Terraform.

If you are up for contributing to this provider, we will happily review any contributions!

**Comment by mikehale** [comment]
> This is actually interesting and a bit tricky.
> 
> While the SSL endpoint _addon_ is indeed no longer the preferred choice, the SSL Endpoint API resources (without the addon) are still used to manage certificates for apps in Private Spaces. The CLI figures out which endpoints to use.
> 

Fortunately, this is [officially no longer true](https://devcenter.heroku.com/changelog-items/2095). It actually stopped applying around the end of March, but is called out explicitly in the linked changelog.

I'm actively working to sunset all usages of `/apps/:id/ssl-endpoints` in Private Spaces, so please let me know how I can help.

**Comment by davidji99** [comment]
Closing this as `heroku_ssl` was implemented recently using the SNI endpoints.
