### ISSUE TITLE
Support the namespace attribute when creating addon attachments

### ISSUE THREAD

**Issue by crisp2u** [heroku/terraform-provider-heroku#279]
Hello,

Is it possible to add the `namespace` attribute to the `heroku_addon_attachment` resource to allow for example attachment of specific database credentials ?

This is documented in the Platform API [here](https://devcenter.heroku.com/articles/platform-api-reference#add-on-attachment-createl).
The credentials attachment can be implemented by setting `namespace = "credential: ${var.credential_name}"` as observed [here](https://github.com/heroku/cli/blob/master/packages/addons-v5/commands/addons/attach.js#L20l)

Thanks

**Comment by mars** [comment]
Hi @crisp2u,

Yes, it is possible to add the `namespace` attribute to `heroku_addon_attachment`, so that it is specified during the attachment creation.

We openly welcome & review pull requests, especially after opening an issue like this to check if a feature/change is possible 😃

**Comment by crisp2u** [comment]
@mars When possible please have a look at the PR :) 

Thanks!

**Comment by davidji99** [comment]
Closing this issue. #280 has been merged and released as part of `v2.6.1`.
