### ISSUE TITLE
heroku_app data resource should have all data provided by the API

### ISSUE THREAD

**Issue by c-carpenter** [heroku/terraform-provider-heroku#285]
### Terraform Version
v0.12.26

### Heroku Provider Version
v2.6.1

### Affected Resource(s)
  - heroku_app

### Terraform Configuration Files
N/A Feature request not a bug.

### Debug Output
N/A Feature request not a bug.

### Panic Output
N/A Feature request not a bug.

### Expected Behavior
What should have happened?
When using the heroku_app data class, all data provided by the Heroku API should be available. https://devcenter.heroku.com/articles/platform-api-reference#app
### Actual Behavior
What actually happened?
A subset of the information provided by the API is available in the data resource. 
https://github.com/heroku/terraform-provider-heroku/blob/master/heroku/resource_heroku_app.go#L564

### Steps to Reproduce
N/A Feature request not a bug.

### Important Factoids
There are times that the Heroku system refers to the id of resources only, and being able to map from name to id is necessary to make things human readable. In my case, its the logging subsystem and how it forwards log messages to a drain. Many of the log messages include the id but not the name of the resource forwarding the log message. In order to provide proper tagging so the log messages can be search for by resource name I need to be able to map the ID to Name. While this is possible for app name, addon name, and region; it is not for the region name. 

Work around:
To work around the current limitations, I have to call out to the private space to get its app id, and I have to hard code the region name to id.

**Comment by davidji99** [comment]
This can be easily added. We can expose more data for an app from the Platform API.

**Comment by mars** [comment]
As far as I can tell, the request was specifically to get the app's ID in addition to name.

Since [`v5` release of this provider](https://github.com/heroku/terraform-provider-heroku/releases/tag/v5.0.0), the `heroku_app` `id` does contain the ID.
