### ISSUE TITLE
Panic when applying heroku_app resource with TF_LOG=debug

### ISSUE THREAD

**Issue by sheax0r** [heroku/terraform-provider-heroku#293]
### Terraform Version
```
Terraform v0.12.29
+ provider.heroku v3.1.0
```

### Heroku Provider Version

```
Terraform v0.12.29
+ provider.heroku v3.1.0
```

### Affected Resource(s)
- `heroku_app`

### Terraform Configuration Files
```hcl
resource "heroku_app" "myapp" {
  name = "sheatest21123"
  region = "us"
}
```

### Debug Output

https://gist.github.com/sheax0r/ed2902a896964872d6758f76cbab7ed9

### Panic Output
https://gist.github.com/sheax0r/6a5b67ff6ef911a8e67f814752d29a71

### Expected Behavior
Terraform should have created the resource and updated the state.

### Actual Behavior
Terraform created the resource but crashed and did not update the state. Subsequent attempts to create this resource will fail because of conflicts (the app already exists), without manual intervention to either delete the app so it can be recreated, or import the existing resource into the state.

### Steps to Reproduce

1. `export TF_LOG=debug`
1. `terraform apply`

**Comment by davidji99** [comment]
Closing this as #294 is merged and released.
