### ISSUE TITLE
`heroku_domain.sni_endpoint_id` lacks documentation

### ISSUE THREAD

**Issue by brianhelba** [heroku/terraform-provider-heroku#315]
#312 added a new optional `sni_endpoint_id` argument to `heroku_domain`. However, [the documentation for `heroku_domain`](https://github.com/heroku/terraform-provider-heroku/blob/master/docs/resources/domain.md#argument-reference) does not list or describe this argument.

### Heroku Provider Version
```v4.5.0```

### Affected Resource(s)
- `heroku_domain`

**Comment by brianhelba** [comment]
Ping @mikehale / @davidji99 .

**Comment by davidji99** [comment]
We'll update the `heroku_domain` documentation. Thanks!
