### ISSUE TITLE
Addon could not be found. But addon exists in the Heroku addon library.

### ISSUE THREAD

**Issue by paul-bonnel-fr** [heroku/terraform-provider-heroku#366]
Hi there,

I'm trying to add an addon called "rediscloud:30" to my heroku app. Here is the link of the addon : https://elements.heroku.com/addons/rediscloud
Unfortunately the terraform-heroku-provider does not find the addon hence why it could not be added to my heroku app. 

```
Terraform v1.4.0
on darwin_arm64
+ provider registry.terraform.io/heroku/heroku v5.1.12
```

### Terraform Configuration Files
```
provider "heroku" {}

resource "heroku_app" "test-event-bridge" {
  name   = "test-event-bridge"
  region = "us"
  organization {
    name = "my-org"
  }
  config_vars = {
  }
}
# Create a database, and configure the app to use it
resource "heroku_addon" "redis" {
  app_id = heroku_app.hov-event-bridge.id
  plan   = "upstash-redis:free"
}

resource "heroku_addon" "monitoring" {
  app_id = heroku_app.hov-event-bridge.id
  plan   = "papertrail:choklad"
}

resource "heroku_addon" "redis-2" {
  app_id = heroku_app.hov-event-bridge.id
  plan   = "rediscloud:30"
}

resource "heroku_build" "test-event-bridge" {
  app_id = heroku_app.hov-event-bridge.id

  source {
    path = "../app"
  }
}

```

### Debug Output
https://gist.github.com/paul-bonnel-fr/041cc59e199eee547c95ae6a04f6ca87#file-gistfile1-txt

### Expected Behavior
A rediscloud addon should have been added to my heroku app. 

### Actual Behavior
What actually happened?
Terraform could not find the addon named : "rediscloud:30" 

### Steps to Reproduce
1. `terraform apply`

**Comment by mars** [comment]
From your debug output, I see the error is:

```
heroku_addon.redis-2: Creating...
heroku_addon.redis-2: Still creating... [10s elapsed]
╷
│ Error: Error waiting for Addon (b8c9e6ed-d3ad-418f-bf8d-b29e2a474756) to be provisioned: Error retrieving addon: Get "https://api.heroku.com/apps/a78b4f60-142c-4414-bb30-442edb978dc2/addons/b8c9e6ed-d3ad-418f-bf8d-b29e2a474756": Couldn't find that add-on.
│ 
```

So, what this is saying, is that the addon was created but while Heroku was waiting for the provider to provision the plan, the request to check the new addon's status returned an error.

I just verified that this add-on can created via Terraform:
```
heroku_addon.redis-2: Creating...
heroku_addon.redis-2: Still creating... [10s elapsed]
heroku_addon.redis-2: Still creating... [20s elapsed]
heroku_addon.redis-2: Still creating... [30s elapsed]
heroku_addon.redis-2: Creation complete after 36s [id=9502cca6-6afa-4db8-bfe2-9036c915c5fa]
```

This was probably a momentary glitch in a service, which caused Terraform to give up.

Did you retry the `terraform apply`? In cases like this, a retry will likely succeed.

**Comment by paul-bonnel-fr** [comment]
Thank you for your anwser, really appreciate it. Indeed it seems like a heroku glitch because this addon can not be added manually trough the heroku UI... weird...

**Comment by mars** [comment]
So, did Terraform end-up working to provision the add-on?

If you have issues with creating or managing an add-on through Heroku Web Dashboard or CLI, then please reach out to https://heroku.support

**Comment by paul-bonnel-fr** [comment]
No terraform did not deployed the `rediscloud:30`addon. You are rightn it seems like this one is on heroku side.  Thanks.
