### ISSUE TITLE
Wait for ACM (Automated Certificate Management)?

### ISSUE THREAD

**Issue by dentarg** [heroku/terraform-provider-heroku#374]
It would be cool if it was possible to understand when the [ACM](https://devcenter.heroku.com/articles/automated-certificate-management#view-your-certificate-status) TLS certificate for my (newly created) app is ready – so I could delay the deploy/build of other apps until that has happened.

I know the docs say

> It usually takes between 45 and 60 minutes to generate a TLS certificate for your app’s custom domains.

but in my experience it is much quicker.

**Comment by mars** [comment]
Hi @dentarg 😄 

It's possible to use Terraform's `provisioner` meta-attribute to know when the app starts responding to its HTTPS URL.

See the [Dev Center article for an example provisioner health check](https://devcenter.heroku.com/articles/using-terraform-with-heroku#use-provisioner-health-checks).
