### ISSUE TITLE
CI failing on `main` with: "Error creating addon heroku-postgresql:mini"

### ISSUE THREAD

**Issue by edmorley** [heroku/terraform-provider-heroku#386]
CI for this repo is failing on `main`, with:

```
Error: Error creating addon heroku-postgresql:mini for app tftest-zyg0bys2o7 (4174a08b-c9bb-4853-a1b1-f3259c74c044):
Post "https://api.heroku.com/apps/4174a08b-c9bb-4853-a1b1-f3259c74c044/addons": 
We tried to create heroku-postgresql:mini, but received an error from the add-on provider. 
Try the request again, or log a support ticket and include this message: 
The mini plan has reached end-of-life. You can try again with a valid plan. 
See the available plans with: heroku addons:plans heroku-postgresql.
```

eg:
https://github.com/heroku/terraform-provider-heroku/actions/runs/9956698200/job/27507166827#step:7:46

This is due to:
https://devcenter.heroku.com/changelog-items/2889

These references to the old plan names will need updating:
https://github.com/search?q=repo%3Aheroku%2Fterraform-provider-heroku+%22heroku-postgresql%3Amini%22&type=code

Ideally the exact plan size would be omitted from the tests, so that they use the default plan size (which is typically the smallest), which will save having to update the tests should the name change again in the future :-)

**Comment by mars** [comment]
@edmorley thanks for the maintenance work on this repo 💜 Please review/approve the Postgres plan fix in #387.
